[package]
name = "rust_winapi"
version = "0.1.0"
authors = ["hyunjun529 <hyunjun529@gmail.com>"]
edition = "2018"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.8", features = ["winuser", "libloaderapi"] }

[dependencies]
rust_common = { path = "../rust_common"}